# Generated by Django 5.2.15 on 2026-06-26 13:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=9, unique=True, verbose_name='Табельный номер')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='СНИЛС')),
                ('address', models.TextField(blank=True, verbose_name='Подразделение и должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_seller', models.BooleanField(default=False, verbose_name='Ответственный за охрану труда')),
                ('is_buyer', models.BooleanField(default=True, verbose_name='Требуется контроль')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Номенклатурный код')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'СИЗ',
                'verbose_name_plural': 'средства индивидуальной защиты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код программы')),
                ('unit', models.CharField(default='курс', max_length=20, verbose_name='Единица учета')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Плановая стоимость')),
            ],
            options={
                'verbose_name': 'программа обучения',
                'verbose_name_plural': 'программы обучения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'проверка',
                'verbose_name_plural': 'проверки условий труда',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('new', 'Запланирован'), ('work', 'Проводится'), ('done', 'Завершен')], default='new', max_length=10, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'инструктаж',
                'verbose_name_plural': 'инструктажи',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество сотрудников')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость обучения')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Инструктаж')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'строка инструктажа',
                'verbose_name_plural': 'строки инструктажа',
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Рекомендованное СИЗ')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.production', verbose_name='Проверка')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество замечаний')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Выявленный риск')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.production', verbose_name='Проверка')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название нормы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'норма обеспечения',
                'verbose_name_plural': 'нормы обеспечения',
            },
        ),
        migrations.CreateModel(
            name='SpecificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество по норме')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='СИЗ')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.specification', verbose_name='Норма')),
            ],
            options={
                'verbose_name': 'позиция нормы',
                'verbose_name_plural': 'состав нормы',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=10, verbose_name='Роль')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Ошибок входа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('number', 'date'), name='unique_order_number'),
        ),
        migrations.AddConstraint(
            model_name='specificationitem',
            constraint=models.UniqueConstraint(fields=('specification', 'material'), name='unique_material_in_specification'),
        ),
    ]
